site: ctf.amanroy.me
title: ctf.amanroy.me
greetings: Capture The Flag
description: >-
  U29sdmluZyBvbmUgQ1RGIGF0IGEgdGltZSBhbmQgZG9jdW1lbnRpbmcgaXQgYWxvbmcgdGhlIHdheS4=
lang: en-US
timezone:  Europe/Rome
repo: https://github.com/p0wex/Gesko # site repo [optional]
data-theme: dark # default theme "dark" | "light"

author:
  name: Aman Roy
  bio: Sucker for flags!
  userpicture: 
  username: amanroy
  github: aman-roy
  twitter: Amanroy_geek
  email: admin@amanroy.me # email adress

# Font Settings
googlewebfonts: family=Play:wght@400;700&family=Source+Code+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,300;1,400;1,500;1,600;1,700;1,900

# URL settings
url: "https://ctf.amanroy.me" # Domain Name of host. [username].github.io for github pages
baseurl: "" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty

# local
# url: "http://localhost:4000" # 
# baseurl: "" # 


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false


